# -*- coding: utf-8 -*-
"""basic01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kwFbNJPDwKE7Y4tsaEIQfrUop7AizFCi

Practice creating variables
"""

first_name = 'Sarah'
firstName = "Sarah"
FirstName = 'Sarah'
FIRSTNAME = 'Sarah'

print(first_name)

last_name = "May"
lastName = "Rehman"
LastName = "Smith"

import math
print(math.pi)

"""10 lists"""

red_fruit = ["apple", "strawberry", "cherry"]
green_vegetables = ["green pepper", "celery"]
farm_animals = ['pigs', 'cows', 'chickens']
shapes = ['triangle', 'circle', 'rectangle']
colors = ['red', 'orange', 'yellow', 'green']
states = ['Texas', 'New York']
trees = ['maple', 'oak']
even_ints = [2, 4, 6, 8]
odd_ints = [3, 5, 7]
months = ['January', 'February']

"""10 bools"""

not_true = not True
true = True
false = False
not_false = not False
not_true2 = 2 + 5 == 11
true2 = 2 * 5 == 10
true3 = True or False
true4 = True and True
false2 = True and False
false3 = 5 != 5

"""10 floats"""

flt1 = 1.1
flt2 = 1.11
flt3 = 1.111
flt4 = 1.123
flt5 = 1.5
flt6 = 1.6
flt7 = 7.0
flt8 = 8.8
flt9 = 9.001
flt10 = 10.10

"""3 dictionaries"""

ten_foods = {"sandwiches": ["chicken salad", "grilled cheese", "ham"], "fruit": ["grapes", "mangos"], "herb": "basil", "condiment": "ketchup"}
ten_people = {"a_name": "Ashley", "b_name": "Ben", "c_name": "Chris", "d_name": "Dennis", "e_name": "Eric", "f_name": "Frank", "g_name": "Gary", "h_name": "Henry", "i_name": "Ivan", "j_name": "Jeremy"}
# I don't know sports players, so I am creating a dictionary of seasonal sports instead.
five_sports = {"winter": "hockey", "fall": "football", "spring": ["basketball", "tennis"], "summer": "swimming"}
print(ten_foods)
print(ten_people)
print(five_sports)