family_members = ['Sarah', 'Scott', 'Kaia', 'Finley', 'Gulzar', 'Diane', 'Jill', 'David', 'Noah', 'Ari', 'Alyssa', 'Louis', 'Zoe', 'Habiba', 'Jalal', 'Aziz', 'Noorallah', 'Nazlin', 'Shazia', 'Tahseen']
print(family_members[0:2])
print(family_members[:2])
print(family_members[0:-2])
print(family_members[5:])
print(family_members[5:7])
print(family_members[0:2])
print(family_members[0:10:2])
print(family_members[0:10:4])
print(family_members[:10:4])
print(family_members[1:9:2])